/// Generated gRPC types for the anvil API.
///
/// The code is generated by tonic and can't be refactored to meet the
/// complexity limits in `clippy.toml`.
#[allow(
    clippy::excessive_nesting,
    clippy::too_many_arguments,
    clippy::too_many_lines
)]
pub mod api {
    tonic::include_proto!("anvil");
}

pub mod runtime;
pub mod sandboxes;
pub mod secrets;
pub mod server;
mod session;
pub mod ssh;
mod tunnel;
pub mod vscode;
