[workspace]
resolver = "3"
members = [
    "crates/cli",
    "crates/daemon",
    "crates/proto",
    "crates/spec",
    "crates/utils",
]

[workspace.dependencies]
firebrick-proto = { path = "crates/proto", version = "0.4.0" }
firebrick-spec = { path = "crates/spec", version = "0.4.0" }
firebrick-utils = { path = "crates/utils", version = "0.4.0" }

[workspace.package]
version = "0.4.0"
authors = ["Willem Meints"]
edition = "2024"
license = "MIT"
repository = "https://github.com/wmeints/anvil"

[workspace.lints.clippy]
too_many_lines = "warn"           # pedantic, so off by default
excessive_nesting = "warn"        # restriction, so off by default
too_many_arguments = "warn"       # on by default; listed for clarity
fn_params_excessive_bools = "warn"
