# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  build:
    desc: Compile the application
    cmds:
      - go build -o bin/anvil ./cmd/anvil/
  lint:
    desc: Run golangci-lint against all source files
    cmds:
      - golangci-lint run ./...
  format:
    desc: Run golangci-lint to format all source files
    cmds:
      - golangci-lint fmt ./...
  test:
    desc: Run the unit-tests for all packages
    cmds:
      - go test ./...
  test:integration:
    desc: Run the integration tests (requires containerd)
    cmds:
      - go test -tags integration ./...
