//! Generated gRPC client and server code for the firebrick daemon API, shared
//! by the `fbk` CLI and the `fbkd` daemon.
//!
//! The code is generated by tonic from `proto/daemon.v1.proto` and can't be
//! refactored to meet the complexity limits in `clippy.toml`.
#![allow(
    clippy::excessive_nesting,
    clippy::too_many_arguments,
    clippy::too_many_lines
)]

tonic::include_proto!("firebrick");
