pub mod client;
pub mod manage;
pub mod secret;
pub mod session;
pub mod ssh;
pub mod table;
pub mod validate;

/// Generated gRPC types for the firebrick API.
///
/// The code is generated by tonic and can't be refactored to meet the
/// complexity limits in `clippy.toml`.
#[allow(
    clippy::excessive_nesting,
    clippy::too_many_arguments,
    clippy::too_many_lines
)]
pub mod api {
    tonic::include_proto!("firebrick");
}
