// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: anvil.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_anvil_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_anvil_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSandboxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSandboxRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type CreateSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxResponse) Reset() {
	*x = CreateSandboxResponse{}
	mi := &file_anvil_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxResponse) ProtoMessage() {}

func (x *CreateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxResponse.ProtoReflect.Descriptor instead.
func (*CreateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_anvil_proto_rawDescGZIP(), []int{1}
}

type ListSandboxesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesRequest) Reset() {
	*x = ListSandboxesRequest{}
	mi := &file_anvil_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesRequest) ProtoMessage() {}

func (x *ListSandboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesRequest.ProtoReflect.Descriptor instead.
func (*ListSandboxesRequest) Descriptor() ([]byte, []int) {
	return file_anvil_proto_rawDescGZIP(), []int{2}
}

type ListSandboxesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandboxes     []*SandboxSummary      `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesResponse) Reset() {
	*x = ListSandboxesResponse{}
	mi := &file_anvil_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesResponse) ProtoMessage() {}

func (x *ListSandboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesResponse.ProtoReflect.Descriptor instead.
func (*ListSandboxesResponse) Descriptor() ([]byte, []int) {
	return file_anvil_proto_rawDescGZIP(), []int{3}
}

func (x *ListSandboxesResponse) GetSandboxes() []*SandboxSummary {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

type SandboxSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxSummary) Reset() {
	*x = SandboxSummary{}
	mi := &file_anvil_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxSummary) ProtoMessage() {}

func (x *SandboxSummary) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxSummary.ProtoReflect.Descriptor instead.
func (*SandboxSummary) Descriptor() ([]byte, []int) {
	return file_anvil_proto_rawDescGZIP(), []int{4}
}

func (x *SandboxSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSandboxRequest) Reset() {
	*x = RemoveSandboxRequest{}
	mi := &file_anvil_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSandboxRequest) ProtoMessage() {}

func (x *RemoveSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSandboxRequest.ProtoReflect.Descriptor instead.
func (*RemoveSandboxRequest) Descriptor() ([]byte, []int) {
	return file_anvil_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveSandboxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSandboxResponse) Reset() {
	*x = RemoveSandboxResponse{}
	mi := &file_anvil_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSandboxResponse) ProtoMessage() {}

func (x *RemoveSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSandboxResponse.ProtoReflect.Descriptor instead.
func (*RemoveSandboxResponse) Descriptor() ([]byte, []int) {
	return file_anvil_proto_rawDescGZIP(), []int{6}
}

type StopSandboxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Time the processes get to exit after SIGTERM before they're killed. An
	// unset or non-positive timeout kills them right away.
	Timeout       *durationpb.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSandboxRequest) Reset() {
	*x = StopSandboxRequest{}
	mi := &file_anvil_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSandboxRequest) ProtoMessage() {}

func (x *StopSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSandboxRequest.ProtoReflect.Descriptor instead.
func (*StopSandboxRequest) Descriptor() ([]byte, []int) {
	return file_anvil_proto_rawDescGZIP(), []int{7}
}

func (x *StopSandboxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StopSandboxRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type StopSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSandboxResponse) Reset() {
	*x = StopSandboxResponse{}
	mi := &file_anvil_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSandboxResponse) ProtoMessage() {}

func (x *StopSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSandboxResponse.ProtoReflect.Descriptor instead.
func (*StopSandboxResponse) Descriptor() ([]byte, []int) {
	return file_anvil_proto_rawDescGZIP(), []int{8}
}

type StartSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSandboxRequest) Reset() {
	*x = StartSandboxRequest{}
	mi := &file_anvil_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSandboxRequest) ProtoMessage() {}

func (x *StartSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSandboxRequest.ProtoReflect.Descriptor instead.
func (*StartSandboxRequest) Descriptor() ([]byte, []int) {
	return file_anvil_proto_rawDescGZIP(), []int{9}
}

func (x *StartSandboxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StartSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSandboxResponse) Reset() {
	*x = StartSandboxResponse{}
	mi := &file_anvil_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSandboxResponse) ProtoMessage() {}

func (x *StartSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSandboxResponse.ProtoReflect.Descriptor instead.
func (*StartSandboxResponse) Descriptor() ([]byte, []int) {
	return file_anvil_proto_rawDescGZIP(), []int{10}
}

type AttachSandboxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AttachSandboxRequest_Start
	//	*AttachSandboxRequest_Input
	//	*AttachSandboxRequest_Resize
	Msg           isAttachSandboxRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachSandboxRequest) Reset() {
	*x = AttachSandboxRequest{}
	mi := &file_anvil_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachSandboxRequest) ProtoMessage() {}

func (x *AttachSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachSandboxRequest.ProtoReflect.Descriptor instead.
func (*AttachSandboxRequest) Descriptor() ([]byte, []int) {
	return file_anvil_proto_rawDescGZIP(), []int{11}
}

func (x *AttachSandboxRequest) GetMsg() isAttachSandboxRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AttachSandboxRequest) GetStart() *AttachStart {
	if x != nil {
		if x, ok := x.Msg.(*AttachSandboxRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *AttachSandboxRequest) GetInput() *SessionInput {
	if x != nil {
		if x, ok := x.Msg.(*AttachSandboxRequest_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *AttachSandboxRequest) GetResize() *WindowSize {
	if x != nil {
		if x, ok := x.Msg.(*AttachSandboxRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isAttachSandboxRequest_Msg interface {
	isAttachSandboxRequest_Msg()
}

type AttachSandboxRequest_Start struct {
	Start *AttachStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type AttachSandboxRequest_Input struct {
	Input *SessionInput `protobuf:"bytes,2,opt,name=input,proto3,oneof"`
}

type AttachSandboxRequest_Resize struct {
	Resize *WindowSize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

func (*AttachSandboxRequest_Start) isAttachSandboxRequest_Msg() {}

func (*AttachSandboxRequest_Input) isAttachSandboxRequest_Msg() {}

func (*AttachSandboxRequest_Resize) isAttachSandboxRequest_Msg() {}

type SessionInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdin         []byte                 `protobuf:"bytes,2,opt,name=stdin,proto3" json:"stdin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInput) Reset() {
	*x = SessionInput{}
	mi := &file_anvil_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInput) ProtoMessage() {}

func (x *SessionInput) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInput.ProtoReflect.Descriptor instead.
func (*SessionInput) Descriptor() ([]byte, []int) {
	return file_anvil_proto_rawDescGZIP(), []int{12}
}

func (x *SessionInput) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

type AttachStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandbox       string                 `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Size          *WindowSize            `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachStart) Reset() {
	*x = AttachStart{}
	mi := &file_anvil_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachStart) ProtoMessage() {}

func (x *AttachStart) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachStart.ProtoReflect.Descriptor instead.
func (*AttachStart) Descriptor() ([]byte, []int) {
	return file_anvil_proto_rawDescGZIP(), []int{13}
}

func (x *AttachStart) GetSandbox() string {
	if x != nil {
		return x.Sandbox
	}
	return ""
}

func (x *AttachStart) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *AttachStart) GetSize() *WindowSize {
	if x != nil {
		return x.Size
	}
	return nil
}

type WindowSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowSize) Reset() {
	*x = WindowSize{}
	mi := &file_anvil_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowSize) ProtoMessage() {}

func (x *WindowSize) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowSize.ProtoReflect.Descriptor instead.
func (*WindowSize) Descriptor() ([]byte, []int) {
	return file_anvil_proto_rawDescGZIP(), []int{14}
}

func (x *WindowSize) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *WindowSize) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type AttachSandboxResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AttachSandboxResponse_Stdout
	//	*AttachSandboxResponse_ExitCode
	Msg           isAttachSandboxResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachSandboxResponse) Reset() {
	*x = AttachSandboxResponse{}
	mi := &file_anvil_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachSandboxResponse) ProtoMessage() {}

func (x *AttachSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anvil_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachSandboxResponse.ProtoReflect.Descriptor instead.
func (*AttachSandboxResponse) Descriptor() ([]byte, []int) {
	return file_anvil_proto_rawDescGZIP(), []int{15}
}

func (x *AttachSandboxResponse) GetMsg() isAttachSandboxResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AttachSandboxResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Msg.(*AttachSandboxResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *AttachSandboxResponse) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Msg.(*AttachSandboxResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

type isAttachSandboxResponse_Msg interface {
	isAttachSandboxResponse_Msg()
}

type AttachSandboxResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type AttachSandboxResponse_ExitCode struct {
	ExitCode int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

func (*AttachSandboxResponse_Stdout) isAttachSandboxResponse_Msg() {}

func (*AttachSandboxResponse_ExitCode) isAttachSandboxResponse_Msg() {}

var File_anvil_proto protoreflect.FileDescriptor

const file_anvil_proto_rawDesc = "" +
	"\n" +
	"\vanvil.proto\x12\x12api.anvil.v1alpha1\x1a\x1egoogle/protobuf/duration.proto\"@\n" +
	"\x14CreateSandboxRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\"\x17\n" +
	"\x15CreateSandboxResponse\"\x16\n" +
	"\x14ListSandboxesRequest\"Y\n" +
	"\x15ListSandboxesResponse\x12@\n" +
	"\tsandboxes\x18\x01 \x03(\v2\".api.anvil.v1alpha1.SandboxSummaryR\tsandboxes\"$\n" +
	"\x0eSandboxSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"*\n" +
	"\x14RemoveSandboxRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x17\n" +
	"\x15RemoveSandboxResponse\"]\n" +
	"\x12StopSandboxRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\x15\n" +
	"\x13StopSandboxResponse\")\n" +
	"\x13StartSandboxRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14StartSandboxResponse\"\xca\x01\n" +
	"\x14AttachSandboxRequest\x127\n" +
	"\x05start\x18\x01 \x01(\v2\x1f.api.anvil.v1alpha1.AttachStartH\x00R\x05start\x128\n" +
	"\x05input\x18\x02 \x01(\v2 .api.anvil.v1alpha1.SessionInputH\x00R\x05input\x128\n" +
	"\x06resize\x18\x03 \x01(\v2\x1e.api.anvil.v1alpha1.WindowSizeH\x00R\x06resizeB\x05\n" +
	"\x03msg\"$\n" +
	"\fSessionInput\x12\x14\n" +
	"\x05stdin\x18\x02 \x01(\fR\x05stdin\"u\n" +
	"\vAttachStart\x12\x18\n" +
	"\asandbox\x18\x01 \x01(\tR\asandbox\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x122\n" +
	"\x04size\x18\x04 \x01(\v2\x1e.api.anvil.v1alpha1.WindowSizeR\x04sizeJ\x04\b\x03\x10\x04\":\n" +
	"\n" +
	"WindowSize\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\"W\n" +
	"\x15AttachSandboxResponse\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x1d\n" +
	"\texit_code\x18\x02 \x01(\x05H\x00R\bexitCodeB\x05\n" +
	"\x03msg2\xed\x04\n" +
	"\fAnvilService\x12d\n" +
	"\rCreateSandbox\x12(.api.anvil.v1alpha1.CreateSandboxRequest\x1a).api.anvil.v1alpha1.CreateSandboxResponse\x12d\n" +
	"\rListSandboxes\x12(.api.anvil.v1alpha1.ListSandboxesRequest\x1a).api.anvil.v1alpha1.ListSandboxesResponse\x12d\n" +
	"\rRemoveSandbox\x12(.api.anvil.v1alpha1.RemoveSandboxRequest\x1a).api.anvil.v1alpha1.RemoveSandboxResponse\x12^\n" +
	"\vStopSandbox\x12&.api.anvil.v1alpha1.StopSandboxRequest\x1a'.api.anvil.v1alpha1.StopSandboxResponse\x12a\n" +
	"\fStartSandbox\x12'.api.anvil.v1alpha1.StartSandboxRequest\x1a(.api.anvil.v1alpha1.StartSandboxResponse\x12h\n" +
	"\rAttachSandbox\x12(.api.anvil.v1alpha1.AttachSandboxRequest\x1a).api.anvil.v1alpha1.AttachSandboxResponse(\x010\x01B0Z.github.com/wmeints/anvil/api/v1alpha1;v1alpha1b\x06proto3"

var (
	file_anvil_proto_rawDescOnce sync.Once
	file_anvil_proto_rawDescData []byte
)

func file_anvil_proto_rawDescGZIP() []byte {
	file_anvil_proto_rawDescOnce.Do(func() {
		file_anvil_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anvil_proto_rawDesc), len(file_anvil_proto_rawDesc)))
	})
	return file_anvil_proto_rawDescData
}

var file_anvil_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_anvil_proto_goTypes = []any{
	(*CreateSandboxRequest)(nil),  // 0: api.anvil.v1alpha1.CreateSandboxRequest
	(*CreateSandboxResponse)(nil), // 1: api.anvil.v1alpha1.CreateSandboxResponse
	(*ListSandboxesRequest)(nil),  // 2: api.anvil.v1alpha1.ListSandboxesRequest
	(*ListSandboxesResponse)(nil), // 3: api.anvil.v1alpha1.ListSandboxesResponse
	(*SandboxSummary)(nil),        // 4: api.anvil.v1alpha1.SandboxSummary
	(*RemoveSandboxRequest)(nil),  // 5: api.anvil.v1alpha1.RemoveSandboxRequest
	(*RemoveSandboxResponse)(nil), // 6: api.anvil.v1alpha1.RemoveSandboxResponse
	(*StopSandboxRequest)(nil),    // 7: api.anvil.v1alpha1.StopSandboxRequest
	(*StopSandboxResponse)(nil),   // 8: api.anvil.v1alpha1.StopSandboxResponse
	(*StartSandboxRequest)(nil),   // 9: api.anvil.v1alpha1.StartSandboxRequest
	(*StartSandboxResponse)(nil),  // 10: api.anvil.v1alpha1.StartSandboxResponse
	(*AttachSandboxRequest)(nil),  // 11: api.anvil.v1alpha1.AttachSandboxRequest
	(*SessionInput)(nil),          // 12: api.anvil.v1alpha1.SessionInput
	(*AttachStart)(nil),           // 13: api.anvil.v1alpha1.AttachStart
	(*WindowSize)(nil),            // 14: api.anvil.v1alpha1.WindowSize
	(*AttachSandboxResponse)(nil), // 15: api.anvil.v1alpha1.AttachSandboxResponse
	(*durationpb.Duration)(nil),   // 16: google.protobuf.Duration
}
var file_anvil_proto_depIdxs = []int32{
	4,  // 0: api.anvil.v1alpha1.ListSandboxesResponse.sandboxes:type_name -> api.anvil.v1alpha1.SandboxSummary
	16, // 1: api.anvil.v1alpha1.StopSandboxRequest.timeout:type_name -> google.protobuf.Duration
	13, // 2: api.anvil.v1alpha1.AttachSandboxRequest.start:type_name -> api.anvil.v1alpha1.AttachStart
	12, // 3: api.anvil.v1alpha1.AttachSandboxRequest.input:type_name -> api.anvil.v1alpha1.SessionInput
	14, // 4: api.anvil.v1alpha1.AttachSandboxRequest.resize:type_name -> api.anvil.v1alpha1.WindowSize
	14, // 5: api.anvil.v1alpha1.AttachStart.size:type_name -> api.anvil.v1alpha1.WindowSize
	0,  // 6: api.anvil.v1alpha1.AnvilService.CreateSandbox:input_type -> api.anvil.v1alpha1.CreateSandboxRequest
	2,  // 7: api.anvil.v1alpha1.AnvilService.ListSandboxes:input_type -> api.anvil.v1alpha1.ListSandboxesRequest
	5,  // 8: api.anvil.v1alpha1.AnvilService.RemoveSandbox:input_type -> api.anvil.v1alpha1.RemoveSandboxRequest
	7,  // 9: api.anvil.v1alpha1.AnvilService.StopSandbox:input_type -> api.anvil.v1alpha1.StopSandboxRequest
	9,  // 10: api.anvil.v1alpha1.AnvilService.StartSandbox:input_type -> api.anvil.v1alpha1.StartSandboxRequest
	11, // 11: api.anvil.v1alpha1.AnvilService.AttachSandbox:input_type -> api.anvil.v1alpha1.AttachSandboxRequest
	1,  // 12: api.anvil.v1alpha1.AnvilService.CreateSandbox:output_type -> api.anvil.v1alpha1.CreateSandboxResponse
	3,  // 13: api.anvil.v1alpha1.AnvilService.ListSandboxes:output_type -> api.anvil.v1alpha1.ListSandboxesResponse
	6,  // 14: api.anvil.v1alpha1.AnvilService.RemoveSandbox:output_type -> api.anvil.v1alpha1.RemoveSandboxResponse
	8,  // 15: api.anvil.v1alpha1.AnvilService.StopSandbox:output_type -> api.anvil.v1alpha1.StopSandboxResponse
	10, // 16: api.anvil.v1alpha1.AnvilService.StartSandbox:output_type -> api.anvil.v1alpha1.StartSandboxResponse
	15, // 17: api.anvil.v1alpha1.AnvilService.AttachSandbox:output_type -> api.anvil.v1alpha1.AttachSandboxResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_anvil_proto_init() }
func file_anvil_proto_init() {
	if File_anvil_proto != nil {
		return
	}
	file_anvil_proto_msgTypes[11].OneofWrappers = []any{
		(*AttachSandboxRequest_Start)(nil),
		(*AttachSandboxRequest_Input)(nil),
		(*AttachSandboxRequest_Resize)(nil),
	}
	file_anvil_proto_msgTypes[15].OneofWrappers = []any{
		(*AttachSandboxResponse_Stdout)(nil),
		(*AttachSandboxResponse_ExitCode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anvil_proto_rawDesc), len(file_anvil_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anvil_proto_goTypes,
		DependencyIndexes: file_anvil_proto_depIdxs,
		MessageInfos:      file_anvil_proto_msgTypes,
	}.Build()
	File_anvil_proto = out.File
	file_anvil_proto_goTypes = nil
	file_anvil_proto_depIdxs = nil
}
