// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: anvil.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnvilService_CreateSandbox_FullMethodName = "/api.anvil.v1alpha1.AnvilService/CreateSandbox"
	AnvilService_ListSandboxes_FullMethodName = "/api.anvil.v1alpha1.AnvilService/ListSandboxes"
	AnvilService_RemoveSandbox_FullMethodName = "/api.anvil.v1alpha1.AnvilService/RemoveSandbox"
	AnvilService_StopSandbox_FullMethodName   = "/api.anvil.v1alpha1.AnvilService/StopSandbox"
	AnvilService_StartSandbox_FullMethodName  = "/api.anvil.v1alpha1.AnvilService/StartSandbox"
	AnvilService_AttachSandbox_FullMethodName = "/api.anvil.v1alpha1.AnvilService/AttachSandbox"
)

// AnvilServiceClient is the client API for AnvilService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnvilServiceClient interface {
	CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error)
	ListSandboxes(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error)
	RemoveSandbox(ctx context.Context, in *RemoveSandboxRequest, opts ...grpc.CallOption) (*RemoveSandboxResponse, error)
	StopSandbox(ctx context.Context, in *StopSandboxRequest, opts ...grpc.CallOption) (*StopSandboxResponse, error)
	StartSandbox(ctx context.Context, in *StartSandboxRequest, opts ...grpc.CallOption) (*StartSandboxResponse, error)
	AttachSandbox(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachSandboxRequest, AttachSandboxResponse], error)
}

type anvilServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnvilServiceClient(cc grpc.ClientConnInterface) AnvilServiceClient {
	return &anvilServiceClient{cc}
}

func (c *anvilServiceClient) CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSandboxResponse)
	err := c.cc.Invoke(ctx, AnvilService_CreateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anvilServiceClient) ListSandboxes(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSandboxesResponse)
	err := c.cc.Invoke(ctx, AnvilService_ListSandboxes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anvilServiceClient) RemoveSandbox(ctx context.Context, in *RemoveSandboxRequest, opts ...grpc.CallOption) (*RemoveSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSandboxResponse)
	err := c.cc.Invoke(ctx, AnvilService_RemoveSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anvilServiceClient) StopSandbox(ctx context.Context, in *StopSandboxRequest, opts ...grpc.CallOption) (*StopSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopSandboxResponse)
	err := c.cc.Invoke(ctx, AnvilService_StopSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anvilServiceClient) StartSandbox(ctx context.Context, in *StartSandboxRequest, opts ...grpc.CallOption) (*StartSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSandboxResponse)
	err := c.cc.Invoke(ctx, AnvilService_StartSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anvilServiceClient) AttachSandbox(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachSandboxRequest, AttachSandboxResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AnvilService_ServiceDesc.Streams[0], AnvilService_AttachSandbox_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AttachSandboxRequest, AttachSandboxResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnvilService_AttachSandboxClient = grpc.BidiStreamingClient[AttachSandboxRequest, AttachSandboxResponse]

// AnvilServiceServer is the server API for AnvilService service.
// All implementations must embed UnimplementedAnvilServiceServer
// for forward compatibility.
type AnvilServiceServer interface {
	CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error)
	ListSandboxes(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error)
	RemoveSandbox(context.Context, *RemoveSandboxRequest) (*RemoveSandboxResponse, error)
	StopSandbox(context.Context, *StopSandboxRequest) (*StopSandboxResponse, error)
	StartSandbox(context.Context, *StartSandboxRequest) (*StartSandboxResponse, error)
	AttachSandbox(grpc.BidiStreamingServer[AttachSandboxRequest, AttachSandboxResponse]) error
	mustEmbedUnimplementedAnvilServiceServer()
}

// UnimplementedAnvilServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnvilServiceServer struct{}

func (UnimplementedAnvilServiceServer) CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSandbox not implemented")
}
func (UnimplementedAnvilServiceServer) ListSandboxes(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSandboxes not implemented")
}
func (UnimplementedAnvilServiceServer) RemoveSandbox(context.Context, *RemoveSandboxRequest) (*RemoveSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSandbox not implemented")
}
func (UnimplementedAnvilServiceServer) StopSandbox(context.Context, *StopSandboxRequest) (*StopSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopSandbox not implemented")
}
func (UnimplementedAnvilServiceServer) StartSandbox(context.Context, *StartSandboxRequest) (*StartSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSandbox not implemented")
}
func (UnimplementedAnvilServiceServer) AttachSandbox(grpc.BidiStreamingServer[AttachSandboxRequest, AttachSandboxResponse]) error {
	return status.Error(codes.Unimplemented, "method AttachSandbox not implemented")
}
func (UnimplementedAnvilServiceServer) mustEmbedUnimplementedAnvilServiceServer() {}
func (UnimplementedAnvilServiceServer) testEmbeddedByValue()                      {}

// UnsafeAnvilServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnvilServiceServer will
// result in compilation errors.
type UnsafeAnvilServiceServer interface {
	mustEmbedUnimplementedAnvilServiceServer()
}

func RegisterAnvilServiceServer(s grpc.ServiceRegistrar, srv AnvilServiceServer) {
	// If the following call panics, it indicates UnimplementedAnvilServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnvilService_ServiceDesc, srv)
}

func _AnvilService_CreateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnvilServiceServer).CreateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnvilService_CreateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnvilServiceServer).CreateSandbox(ctx, req.(*CreateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnvilService_ListSandboxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSandboxesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnvilServiceServer).ListSandboxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnvilService_ListSandboxes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnvilServiceServer).ListSandboxes(ctx, req.(*ListSandboxesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnvilService_RemoveSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnvilServiceServer).RemoveSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnvilService_RemoveSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnvilServiceServer).RemoveSandbox(ctx, req.(*RemoveSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnvilService_StopSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnvilServiceServer).StopSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnvilService_StopSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnvilServiceServer).StopSandbox(ctx, req.(*StopSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnvilService_StartSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnvilServiceServer).StartSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnvilService_StartSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnvilServiceServer).StartSandbox(ctx, req.(*StartSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnvilService_AttachSandbox_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnvilServiceServer).AttachSandbox(&grpc.GenericServerStream[AttachSandboxRequest, AttachSandboxResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnvilService_AttachSandboxServer = grpc.BidiStreamingServer[AttachSandboxRequest, AttachSandboxResponse]

// AnvilService_ServiceDesc is the grpc.ServiceDesc for AnvilService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnvilService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.anvil.v1alpha1.AnvilService",
	HandlerType: (*AnvilServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSandbox",
			Handler:    _AnvilService_CreateSandbox_Handler,
		},
		{
			MethodName: "ListSandboxes",
			Handler:    _AnvilService_ListSandboxes_Handler,
		},
		{
			MethodName: "RemoveSandbox",
			Handler:    _AnvilService_RemoveSandbox_Handler,
		},
		{
			MethodName: "StopSandbox",
			Handler:    _AnvilService_StopSandbox_Handler,
		},
		{
			MethodName: "StartSandbox",
			Handler:    _AnvilService_StartSandbox_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AttachSandbox",
			Handler:       _AnvilService_AttachSandbox_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "anvil.proto",
}
