[package]
name = "firebrick-proto"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Generated gRPC client and server code for the Firebrick daemon API."

[lints]
workspace = true

[dependencies]
prost = "0.14.4"
tonic = "0.14.6"
tonic-prost = "0.14.6"

[build-dependencies]
tonic-prost-build = "0.14.6"
